### ISSUE TITLE
Remote

### ISSUE THREAD

**Issue by jbeck22** [Kibibit/hass-kibibit-theme#1]
Do you have the code available for the Plex remote that you show in the screenshots?  I use Plex and really like this theme and esp. that remote that you show.  Great work!

**Comment by Thatkookooguy** [comment]
Sure. I'll send you something detailed (here, or on the forums and just post a link here) if you still want it

**Comment by Thatkookooguy** [comment]
Just notice that I use my Logitech Harmony to control my PC. But if you don't have one, it's simple to change the commands to use something else

**Comment by Thatkookooguy** [comment]
Ok, so until I make a post in the home assistant community, here's the gist of it!

This is the basic plex remote if that's what you want:
```yaml
cards:
  - entity: media_player.plex_plex_media_player_neil_gaming_pc
    name: Plex Media Player (PC)
    type: 'custom:mini-media-player'
  - buttons:
      - entity: script.1588710575974
        icon: 'mdi:subtitles'
        name: Cycle Subtitles
        style:
          - color: '#e5a00d'
          - zoom: 120%
      - entity: script.1588720887405
        icon: 'mdi:arrow-left-circle'
        name: Subtitles Delay
        style:
          - color: '#e5a00d'
          - zoom: 120%
      - entity: script.1588711931446
        icon: 'mdi:arrow-right-circle'
        name: Subtitles Delay
        style:
          - color: '#e5a00d'
          - zoom: 120%
    type: 'custom:button-entity-row-fork'
  - buttons:
      - entity: script.1588721059935
        icon: 'mdi:ear-hearing'
        name: Cycle Audio
        style:
          - color: '#00d1b2'
          - zoom: 120%
      - entity: script.1588720980481
        icon: 'mdi:arrow-left-circle'
        name: Audio Delay
        style:
          - color: '#00d1b2'
          - zoom: 120%
      - entity: script.1588720910927
        icon: 'mdi:arrow-right-circle'
        name: Audio Delay
        style:
          - color: '#00d1b2'
          - zoom: 120%
    type: 'custom:button-entity-row-fork'
  - cards:
      - color: 'hsl(348, 100%, 61%)'
        color_type: icon
        icon: 'mdi:backspace'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: Back
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
      - color: auto
        color_type: red
        icon: 'mdi:arrow-up'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: DirectionUp
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
      - height: 1
        size: 1
        type: 'custom:gap-card'
    type: horizontal-stack
  - cards:
      - color: auto
        color_type: red
        icon: 'mdi:arrow-left'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: DirectionLeft
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
      - color: '#e5a00d'
        color_type: icon
        icon: 'mdi:radiobox-marked'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: OK
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
      - color: auto
        color_type: red
        icon: 'mdi:arrow-right'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: DirectionRight
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: auto
        color_type: auto
        icon: 'mdi:play-pause'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: Play
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
      - color: auto
        color_type: auto
        icon: 'mdi:arrow-down'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: DirectionDown
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
      - color: auto
        color_type: auto
        icon: 'mdi:stop'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: Stop
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
        type: 'custom:button-card'
    type: horizontal-stack
type: vertical-stack
```
It uses the following HACS integrations:
- [custom:mini-media-player](https://github.com/kalkih/mini-media-player) - to show the currently playing track and basic controls
- [custom:button-entity-row-fork](https://github.com/custom-cards/button-entity-row) - to create the button rows for subtitles and audio buttons
- [custom:button-card](https://github.com/custom-cards/button-card) - used to create the big buttons (arrows etc.)
- [custom:gap-card](https://github.com/thomasloven/lovelace-gap-card) - well... for creating gaps :-)

I also mapped some keys in plex in order to control plex using keys that harmony supports. Let me know if you need to change that yourself and I'll post what you need to do if you get stuck.

Also, my remote changes based on the input (you select netflix, plex, etc.) so it shows only the relevant controls. I use it as a universal remote from my phone. If you want more info on how to add additional remotes to the same setup, let me know :-)

**Comment by jbeck22** [comment]
Thanks for the code.  Just to clarify -- this **requires** the Harmony Remote in order to function?

**Comment by Thatkookooguy** [comment]
@jbeck22 no, not at all.
Each button has a `tap_action` field. I specifically call `remote.send_command` and I'm using the **entity_id** for my harmony.
You can use any other remote you integrated with home assistant or any integration that works with PLEX. Take a look at the button-card documentation to see usage examples:
https://github.com/custom-cards/button-card

this is the section that you need to change basically:
```yaml
tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: Stop
            device: Livingroom Windows Computer
            entity_id: remote.harmony_hub
```
for each button

What exactly is your setup? do you have a way to control PLEX remotely at the moment?
