### ISSUE TITLE
theme is lost

### ISSUE THREAD

**Issue by Sebastian-Voigt** [Kibibit/hass-kibibit-theme#191]
Hey, 

I can't find the theme in HACS.

**Comment by woody4165** [comment]
I have it installed from a long time, but now I get a message in HACS that says that "theme is archived".
Don0t know if it's because it'n not updated from 3-4 years.

In any case you can just copy the content of themes folder here in the themes folder in home-assistant and reload HA.

Of course, you will receive same warning message as I mentioned before

**Comment by lennon101** [comment]
Yeah I just added it as a custom repo in HACS by copying the url of the github page and pasting. Seemed to work. But when I try to use the theme, it looks terrible! There is lots of white on white text and I have these black outlines around the cards. The cards don't have their own theme or anything. I am using some mushroom cards but it should be able to handle it especially if I'm not choosing a seperate theme for each card.

**Comment by BlackRockCity** [comment]
Thanks for explaining why I couldnt find the theme. I wont bother installing it if it is buggy. I note the kibibit frosted cards are still available on HACS

**Comment by iursevla** [comment]
<img width="537" alt="image" src="https://github.com/user-attachments/assets/55bc50cf-cd69-4c2a-9276-3d28872521ec">

**Comment by churchofnoise** [comment]
Slight update - I was in touch with the creator of this theme, @thatkookooguy  , and he indicated that he intends to pick this up again!
Excellent news I'd say

**Comment by thatkookooguy** [comment]
Yup. Hopefully in December I'll work on this to update it to the new HA themes

**Comment by thatkookooguy** [comment]
Yup. Hopefully in December I'll work on this to update it to the new HA themes

**Comment by steve-prentice** [comment]
Hi @thatkookooguy - I've just found screenshots of this theme and was interested in installing cos it looks great, but have ended up here because I can't find it in HACS... How is the update coming along? :)

**Comment by BlackRockCity** [comment]
@steve-prentice I ended up using the following theme instead. The font and background image stuff is the result of hours of trial and error... my loss is your gain!


https://github.com/basnijholt/lovelace-ios-dark-mode-theme/

place the theme into root/config/themes

Off-topic: install Studio Code Server add-on if your hardware can handle it. It makes all of this way easier.

---

### Changing the Background Image

1. Create a directory named `theme-bg-images` at:
   ```
   /config/www/theme-bg-images/
   ```

2. Place your JPEG background images in that directory.

3. In your theme YAML, add:
   ```yaml
   background-image: "center / cover no-repeat fixed url('/local/theme-bg-images/my-background.jpg')"
   lovelace-background: var(--background-image)
   ```

---

### Changing the Font

Add the following to your theme YAML:
```yaml
ha-font-family: "Futura Book BT, sans-serif"
ha-font-family-body: "Futura Book BT, sans-serif"
ha-font-family-heading: "Futura Book BT, sans-serif"
ha-font-family-mono: "Futura Book BT, monospace"
```

Notes:
- The font must be in `woff2` format.
- Place the font file in:
  ```
  /config/www/
  ```
- A free TrueType to WOFF2 converter [can be found online](https://cloudconvert.com/ttf-to-woff2).
- The default Kibibit font is [Comfortaa](https://fonts.google.com/specimen/Comfortaa).

---

### Home Assistant Configuration

In `configuration.yaml`, add:

```yaml
# THEMES
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/loadfont.js
```

---

### loadfont.js

Create the file:
```
/config/www/loadfont.js
```

Contents:
```js
const css = "/local/fonts.css";

const link = document.createElement("link");
link.rel = "stylesheet";
link.href = css;
document.head.appendChild(link);

console.info("Loaded font CSS:", css);

export {};
```

---

### fonts.css

Create the file:
```
/config/www/fonts.css
```

Contents:
```css
@font-face {
  font-family: "FuturaBookBTCustom";
  src: url("/local/futurabookbt.woff2") format("woff2");
  font-display: swap;
}
```

Do a full reboot of Home Assistant (not just a yaml reload). Settings > Top right corner three dots menu, choose Restart Home Assistant.

Select the theme by going to your profile in the bottom left of the side panel and clicking on your name. Scroll down to set your theme. This must be done on each device which shows a dashboard.
